language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

before script:
  - cd ui

script:
  - npm test
  - npm run build

deploy:
  provider: azure_web_apps
  username: AZ_LOGIN_NAME       # Currently user profile, needs to be updated
  password: AZ_PASSWORD         # Currently user profile, needs to be updated
  local_dir: build
  on:
    branch: feature-thomas-task194 #will say master after testing
