language: node_js
node_js:
  - 12.16.1

#only updates on commits from this brannch and master
branches:
  only:
    - master
    - stor-dev-westus2

#changes directory to the ui branch for website updates
before install:
  - cd ui

#testing to see if npm commands work
script:
  - npm run build
