language: generic
dist: trusty
sudo: required

services:
  - az

branches:
  only:
    - feature-kevin-task5

before_install:
    - AZ_REPO=$(lsb_release -cs)
    - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
    - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get install apt-transport-https azure-cli
    - az --help
    - echo $AZ_LOGIN_NAME
    - echo $AZ_PASSOWRD
    - echo $AZ_TENANT
    - echo $AZURE_STORAGE_ACCOUNT
    - az login -u $AZ_LOGIN_NAME -p $AZ_PASSWORD --service-principal --tenant $AZ_TENANT > /dev/null 2>&1
    - az account show

after_success:
  #- az storage blob upload-batch -d kevinscontainer --account-name $AZURE_STORAGE_ACCOUNT -s directory_path --pattern *.html
  az storage blob upload --file ./devops/azure-TravisCI/index.html --container-name kevinscontainer  --name index
