language: node_js
node_js:
  - 12.16.1

#stores npm data to speed up ci
cache: npm

#only updates on commits from this branch, develop and master
branches:
  only:
    - master
    - develop
    - stor-dev-westus2

######This is what the code looks like before the switchover

# #changes directory to the ui branch for website updates
# before install:
#   - cd ui
#
# #run the build setup in travis ci and remove warnings as errors
# script:
#   - unset CI
#   - npm run build

jobs:
  include:
    - stage: test storage
      before install: cd ui
      script:
        - unset CI
        - npm run build
