language: node_js
node_js:
  - 12.16.1

#stores npm data to speed up ci
cache: npm

#only updates on commits from this branch, develop and master
branches:
  only:
    - master
    - develop
    - stor-dev-westus2

#changes directory to the ui branch for website updates
before install:
  - cd ui

<<<<<<< HEAD
#run the build setup in travis ci and remove warnings as errors
=======
#run the build setup in travis ci, skip tests and remove warnings as errors
>>>>>>> 7c745a4016937bab0fe3fae3f22380740c767279
script:
  - unset CI
  - npm run build
