language: node_js
node_js:
  - "stable"
dist: trusty
sudo: required

branches:
  only:
    - feature-thomas-task194

#changes the directory over to the ui folder
before script:
  - cd ui

#Hard coding only for testing
before_install:
  - AZ_REPO=$(lsb_release -cs)
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install apt-transport-https azure-cli
  - az login -u $AZ_LOGIN_NAME -p $AZ_PASSWORD --service-principal --tenant 08c1c649-bfdd-439e-8e5b-5ff31c72ce4e > /dev/null 2>&1 #$AZ_TENANT

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run build

after_success:
  - az storage blob upload-batch -d \$web -s ./dist/azure-blob

# language: node_js
# node_js:
#   - "stable"
# cache:
#   directories:
#   - node_modules
# script:
#   - npm test
#   - npm run build
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $github_token
#   local_dir: build
#   on:
#     branch: feature-thomas-task194 #master
