language: node_js
node_js:
  - 12.16.1

#only updates on commits from this brannch and master
branches:
  only:
    - master
    - stor-dev-westus2

#changes directory to the ui branch for website updates
before install:
  - cd ui

#saves the node modules to save time loading ci
cache:
  directories:
  - "node_modules"

script:
  - npm run test
