language: node_js
node_js:
  - 12.16.1

#changes direcotry to the ui branch for website updates
before install:
  - cd ui

#saves the node modules to save time loading ci
cache:
  directories:
  - "node_modules"
